source 'https://rubygems.org'

gem 'dotenv'
gem 'rspec'
gem 'rake'
gem 'aws-sdk', '~> 1.0', require: 'aws-sdk'
gem 'net-ssh'
gem 'net-scp'
gem 'colorize'
gem 'capybara'
gem 'selenium-webdriver'
gem 'capybara-selenium'
